apiVersion: v1
kind: Service
metadata:
  name: {{ template "kubernetes.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "kubernetes.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: envoy
  ports:
  - name: envoy
    port: {{ .Values.envoyConfig.port }}
    protocol: TCP
  - name: metrics
    port: {{ .Values.envoyConfig.adminPort }}
    protocol: TCP